### ISSUE TITLE
Doesn't get boards anymore

### ISSUE THREAD

**Issue by borys-pc33** [mheap/trello-cli#112]
In version 0.11.0
```
trello show-boards
```

returns empty, despite if I run

```
trello assigned-to-me
```

It returns
Board: 6169584b5a0b644f35080cd7
* ....
* (list of tasks)

**Comment by mheap** [comment]
The`trello show-boards` command reads from the local board cache. Run `trello refresh boards` then try running `trello show-boards again`

**Comment by borys-pc33** [comment]
Thanks. Works now!

NB: For some reason if Authentication token has expired or is otherwise invalid refresh doesn't clean cache, so I needed to authorize first and then refresh
