### ISSUE TITLE
move-all puts the cards in the bottom of the list

### ISSUE THREAD

**Issue by paolo-bolzoni** [mheap/trello-cli#127]
It would be very useful to be able to put the cards optionally on top

It can even be generalized with a new option where stating the position (e.g., `-p 0` to put in the top)

**Comment by mheap** [comment]
Unfortunately this is a limitation in the Trello API itself. There is no way to specify the position of moved cards:

https://developer.atlassian.com/cloud/trello/rest/api-group-lists/#api-lists-id-archiveallcards-post
