### ISSUE TITLE
Feature: configure config path with environment variable

### ISSUE THREAD

**Issue by zdog234** [mheap/trello-cli#132]
Would it be reasonable to allow overriding the default config path with an environment variable? (say `TRELLO_CLI_CONFIG_FILE`)

This would allow having different config files for different trello accounts, although without having spent enough time tinkering with the tool yet, would this lead to conflicts? (Would we need to implement the ability to configure where local state gets stored?)

**Comment by mheap** [comment]
This seems like a very reasonable request, but also tough. As you expected, local state isn't namespaced at the moment.

**Comment by mheap** [comment]
This is supported in 1.0.0-alpha.1 (through `TRELLO_CLI_PROFILE`), so I'm closing the issue as done and I'll let you know when there's a usable release
