### ISSUE TITLE
Display cards real ID

### ISSUE THREAD

**Issue by Tonus1** [mheap/trello-cli#186]
Hi
While listing cards, a small ID is printed, not the real ID, despite I can show card details using real ID (from 3llo).

```
$ trello show-cards -b 'Board' -l 'My list'
ACCOUNT > Board > My list
* jKSd8V1p - CARD
* ile2QZnr - Some other Card
* wjFrZ5bb - Title
```

```
$ trello card-details 5dadb6ad303db6ad3036698
You are subscribed to this card.
X members: 
Y attachments:
* DOC title - https://cloud.based.in/url

Description here
```

I'd love to combine both tools.
I started a rofi-based script to add a card but miss some habilities 3llo has (multi-line description for instance).

**Comment by mheap** [comment]
trello-cli 1.0.0 was just released, and I think you'll find it useful.

The `card:list` command now outputs full IDs, but there's also a `--format json` option which will allow you to use `jq` to extract IDs as needed.

Let me know if that works for you 😁
