### ISSUE TITLE
Open to incrementally adding autocomplete?

### ISSUE THREAD

**Issue by znd4** [mheap/trello-cli#189]
Hi, would you be open to a contribution adding autocomplete for some shells?

I haven't spent enough time digging into the code yet to give a full rundown of the plan, but at least at a high level, I'm thinking of:

1. adding something like a `__completion_data` subcommand that outputs structured data about the global options, the subcommands, and the subcommands' options and arguments.
2. Write a completion function for each shell that parses that `__completion_data`, accessible as `trello completion <shell>` or `trello completion --shell <zsh>`
3. Document the methods of integrating each shell's completion functions.

I'm most interested in fish, because that's the shell that I'm currently using, and its completion engine seems to be easier to work with, but I'd understand not wanting to merge something like this until bash and zsh are also supported.

**Comment by mheap** [comment]
I've just pushed trello-cli@1.0.0 which includes an `autocomplete` function. Unfortunately, it doesn't look as though oclif supports fish (https://github.com/oclif/plugin-autocomplete/pull/38)

I'd be happy to see fish support if we can figure out how to integrate with `oclif/plugin-autocomplete`

**Comment by znd4** [comment]
ah, thanks!

It looks like there have been a few related PRs ([here](https://github.com/Maastrich/plugin-autocomplete/pull/1) and [here](https://github.com/oclif/plugin-autocomplete/pull/175)) opened since then, but none have been merged. With that in mind, I'll close this issue for now. If, in the future, one of those gets merged, someone can ping here to let you know :)

**Comment by znd4** [comment]
ah, thanks!

It looks like there have been a few related PRs ([here](https://github.com/Maastrich/plugin-autocomplete/pull/1) and [here](https://github.com/oclif/plugin-autocomplete/pull/175)) opened since then, but none have been merged. With that in mind, I'll close this issue for now. If, in the future, one of those gets merged, someone can ping here to let you know :)
