### ISSUE TITLE
Error listing boards

### ISSUE THREAD

**Issue by Cheyans** [mheap/trello-cli#24]
I tried to list the boards as so and got the following error
`trello show-list -b "To Do" -l "Homework"`
 
```/usr/lib/node_modules/trello-cli/src/translator.js:78
    if (boards[i][1].toLowerCase() == name){
                    ^
TypeError: Cannot read property 'toLowerCase' of null
    at Translator.getBoardIdByName (/usr/lib/node_modules/trello-cli/src/translator.js:78:21)
    at Object.cb (/usr/lib/node_modules/trello-cli/src/commands/show-list.js:27:30)
    at Object.ArgParser.parse (/usr/lib/node_modules/trello-cli/node_modules/nomnom/nomnom.js:302:15)
    at Object.<anonymous> (/usr/lib/node_modules/trello-cli/bin/trello:74:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
```

I also tried list the boards without quotes as seen in #3 
`trello show-list -b To\ Do -l Homework`
but got the same error
I did run ```trello refresh all``` before these commands

**Comment by ksk100** [comment]
Hi @Cheyans,

I can reduplicate this message if I use a board name which doesn't exist.

Working:

    C:\users\user\Documents> trello show-list -b "a - GTD" -l "Next actions"
    a - GTD
    * Task one

Doesn't work:

    C:\users\user\Documents> trello show-list -b "NON-EXISTENT BOARD" -l "Next actions"
    if (boards[i][1].toLowerCase() == name){
                    ^
    TypeError: Cannot read property 'toLowerCase' of null
        at Translator.getBoardIdByName (d:\sync\dev\GitHub\trello-cli\src\translator.js:78:21)

Can you confirm that a board with name "To Do" exists?  If so, can you change line 6 and 7 in `logger.js`, commenting out the line with warning, and commenting in the line with debug, and then rerun and see if it prints anything more useful?

Either way, we could definitely do with a more informative error message there, so I'll try to get that sorted out.

**Comment by ksk100** [comment]
Hello again @Cheyans,

I've just done a PR which will now make the `show-list` command (which is better thought of as `show-cards`, and now works under that name) friendlier: it should print a list of your open boards if you mistype the board name.

Let me know how you get on (if/when that PR is accepted).

**Comment by Cheyans** [comment]
I do have a board called "To Do", i'm not sure if trello api uses hyphens or something for spaces and I'll test show-list (when :D) it gets accepted

**Comment by mheap** [comment]
@Cheyans It's been merged! Feel free to give it a go.

Thanks, @ksk100

**Comment by ksk100** [comment]
Spaces shouldn't be a problem, I've got lots of boards/lists with spaces in and I just use quotes.

Let's see if this update helps and go from there.

**Comment by Cheyans** [comment]
Am I understanding something incorrectly here? 
![image](https://cloud.githubusercontent.com/assets/8811789/12629316/51b35994-c515-11e5-8df4-46aa20d6f2cd.png)

**Comment by ksk100** [comment]
You need to supply the name of the list too, then that command will show
all the cards on that list.
