### ISSUE TITLE
Lists are not recognized

### ISSUE THREAD

**Issue by tstrijdhorst** [mheap/trello-cli#39]
I'm trying to do the following testcase but it always replies that the list does not exist when trying to add a card, even though it did create the board / list.

If I use the force option it creates a list with the same name that already exists and then fails again saying the list does not exist so I think there might be going something wrong with the create card API call.

Example flow:
```
~/test/trello-cli master
❯ ./bin/trello add-board -b testboard -d LOL
Organization, board, list, and user cache refreshed

~/test/trello-cli master
❯ ./bin/trello add-list -b testboard -l testlist

~/test/trello-cli master
❯ ./bin/trello add-card -b testboard -l testlist "test from the cli"
error: List 'testlist' does not exist.  Exiting.

~/test/trello-cli master
❯ ./bin/trello add-card "test from the cli" -b "testboard" -l "testlist" -f
Organization, board, list, and user cache refreshed
error: List 'testlist' does not exist.  Exiting.
```

**Comment by mheap** [comment]
Hi @tstrijdhorst,

Thanks for the bug report. I've managed to reproduce the issue following the steps that you provided. Going forward the cache will be updated any time you add a new list automatically. To fix your issue, you'll need to run `./bin/trello refresh lists` after pulling down the latest version on `master`

You can see the fix in this commit https://github.com/mheap/trello-cli/commit/194a1b8e78d1977024986d285e5f90d045580c89

Cheers, Michael
