### ISSUE TITLE
Default configPath is incorrect

### ISSUE THREAD

**Issue by mmahnken** [mheap/trello-cli#5]
The setup instructions need a note to change the default config path from `/home/michael/.trello-cli/`.

**Comment by mheap** [comment]
@mmahnken Only 18 months late, but we've supported this for a while. `trello-cli` will now generate a path based on the current user :)

**Comment by mmahnken** [comment]
Nice! Thanks.

**Comment by blakat360** [comment]
Can we move config path to .config?

**Comment by mheap** [comment]
@blakat360 We'd need to keep the existing path as a fallback so that it doesn't break existing installations.

If you're interested in contributing this please open a PR and I can review it. If not, please open a new issue so we can track it as an enhancement
