### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mathieu-aubin** [mheap/trello-cli#54]
As i am trying to build packages for trello-cli, i am running into a problem a fasr as the license goes.

"BSD" has multiple licenses.
Please update your package.json with your choosen BSD license.

You can find them at https://spdx.org/licenses/

Note - npm also complains (as a warning) about this
"npm WARN trello-cli@0.2.1 license should be a valid SPDX license expression"

**Comment by mheap** [comment]
I've added a `LICENSE` file  - thanks for the heads up https://github.com/mheap/trello-cli/commit/87b24fa7adab57c40dcc263159d1ddffe8dc537e
