### ISSUE TITLE
cannot create a new card

### ISSUE THREAD

**Issue by ZobairQ** [mheap/trello-cli#73]
I was reading the documentation and did run following 
```
trello add-card "some nice title" "some nice description" -b board_name

```
But it was that the arguments do not match. 
--help gives me
```
Usage: trello add-card <title> [description] [options]
```

**Comment by mheap** [comment]
Hey @ZobairQ!

When adding a card to a board you also need to specify the list name e.g.

```
trello add-card "some nice title" "some nice description" -b board_name -l "To Do"
```

The error message isn't the most useful. I'll see what I can do about it
