### ISSUE TITLE
question: is it intended behavior for "trello refresh" to miss archived lists?

### ISSUE THREAD

**Issue by work67** [mheap/trello-cli#80]
see title.
My use case is sometimes I need to access archived lists, but I can't. Cause trello refresh removes them from the cacheFile.
And I don't want to go and manually un-archive them, just to read their cards once.

Is this by design? If not, should be corrected.

We've recently fixed how refresh works in regard to deleted lists/boards, but what about archived ones?
(closed but not deleted boards and archived lists, but not deleted.)

Thanks!

**Comment by mheap** [comment]
This looks like an inconsistency in the Trello API. 

- If you close a board it's still returned via `https://api.trello.com/1/members/me/boards`
- If you archive a list is is not returned via `https://api.trello.com/1/boards/:id/lists`

The solution is to pass `?filter=all` to the lists endpoint. I've just released `v0.5.0` which allows this. It could increase the amount of time taken to sync for those that use a lot of lists so I've added it behind an environment variable. Set `TRELLO_CLI_LIST_FILTER` to `all` to enable this feature ([FAQ](https://github.com/mheap/trello-cli#faq)])
